# Generated by Django 4.2 on 2024-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='year',
            field=models.FloatField(choices=[(1.1, '1.1'), (1.2, '1.2'), (2.1, '2.1'), (2.2, '2.2'), (3.1, '3.2'), (4.1, '4.1'), (4.2, '4.2')], default=0.0, max_length=20),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
