# Generated by Django 4.2 on 2024-09-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_semester_alter_qrcode_lecture_date_unit_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userunit',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.semester'),
        ),
    ]
