# Generated by Django 4.2 on 2024-03-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_unit_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qr_code_image', models.ImageField(upload_to='qr_codes/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.unit')),
            ],
        ),
    ]
