# Generated by Django 4.2 on 2024-09-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_userunit_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='semester',
        ),
    ]
