# Generated by Django 4.2 on 2024-03-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='date',
            new_name='lecture_date',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='unit',
            new_name='unit_code',
        ),
    ]
