from django.urls import path
from . import views
urlpatterns = [
    path('', views.login_request, name='login'),
    path('profile/', views.profile, name='profile'),
    path('home/', views.home, name='home'),
    path('admin-registration/', views.admin_registration, name='admin-registration'),
    path('login/', views.login_request, name='login'),
    path('login/', views.logout_request, name='logout'),
    path('home/student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('home/lecturer_dashboard/', views.lecturer_dashboard, name='lecturer_dashboard'),
    path('home/admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('register_course/', views.choose_and_display_units, name='register_course'),
    path('attendance/', views.attendance, name='attendance'),
    path('register_course/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('register_course/add_to_cart/<int:unit_id>/', views.add_to_cart, name='add_to_cart'),
    path('register_course/selected_units/', views.view_cart, name='selected_units'),
    path('register_course/registered_units/', views.registered_units, name='registered_units'),
    # path('attendance/', views.attendance, name='scan_qr'),
    # path('process_qr_code/', views.process_qr_code, name='process_qr_code'),
    # path('take_attendance/', views.take_attendance, name='take_attendance'),
    # path('generate_qr/', views.generate_qr, name='generate_qr'),
    path('add_user/', views.add_user, name='add_user'),
    # path('attendance_analysis/', views.attendance_analysis, name='A_analysis'),
]
